---
name: Add preview link

on:
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const repo = context.repo.owner + '/' + context.repo.repo;

            const branch = await github.rest.pulls.list({ owner: context.repo.owner, repo: context.repo.repo })
              .then(response => response.data)
              .then(data => data.find(pr => pr.number === context.issue.number))
              .then(pull => pull.head.ref);
            const ref = 'refs/heads/' + branch;

            const datajson = `https://raw.githubusercontent.com/${repo}/${ref}/src/data.json`;
            const datalink = encodeURIComponent(datajson);
            const previewlink = 'https://alexanderthesensei.github.io/map/preview?data=' + datalink;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Предварительный просмотр доступен [здесь](${previewlink})`,
            })
